title: Solver project
description: A page for demonstrating application of solver and problems
theme: just-the-docs

url: https://samhovbproject.github.io/testDocPage

compress_html:
  blanklines: true
